sudo: true
language: bash
services:
- docker

before_install:
- docker -v
- echo $TRAVIS_COMMIT
- export ECR_REPOSITORY=keboola/aws-cloudtrail-slack-hook
- export ECR_REGISTRY="061240556736.dkr.ecr.us-east-1.amazonaws.com/${ECR_REPOSITORY}"
- export ECR_TAG=stage-$TRAVIS_COMMIT

jobs:
  include:
  - stage: build
    before_script:
    - eval $(docker run --rm -i -e AWS_ACCESS_KEY_ID=$ECR_AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$ECR_AWS_SECRET_ACCESS_KEY quay.io/keboola/aws-cli ecr get-login --region us-east-1 --no-include-email)
    - docker pull $ECR_REGISTRY:cache || true
    - docker build --cache-from $ECR_REGISTRY:cache -t $ECR_REPOSITORY .
    - docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY:cache
    - docker push $ECR_REGISTRY:cache
    - docker build -t $ECR_REPOSITORY .
    - docker tag $ECR_REPOSITORY:latest "${ECR_REGISTRY}:${ECR_TAG}"
    - docker push "${ECR_REGISTRY}:${ECR_TAG}"
    script: skip

  - stage: lint
    before_script:
    - eval $(docker run --rm -i -e AWS_ACCESS_KEY_ID=$ECR_AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$ECR_AWS_SECRET_ACCESS_KEY quay.io/keboola/aws-cli ecr get-login --region us-east-1 --no-include-email)
    - docker pull "${ECR_REGISTRY}:${ECR_TAG}"
    script:
    - docker run --rm "${ECR_REGISTRY}:${ECR_TAG}" yarn test:lint

  - stage: tests
    before_script:
    - eval $(docker run --rm -i -e AWS_ACCESS_KEY_ID=$ECR_AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$ECR_AWS_SECRET_ACCESS_KEY quay.io/keboola/aws-cli ecr get-login --region us-east-1 --no-include-email)
    - docker pull "${ECR_REGISTRY}:${ECR_TAG}"
    script:
    - docker run --rm
      -e SLACK_URL
      "${ECR_REGISTRY}:${ECR_TAG}" yarn test:unit

  - stage: deploy
    if: branch = master AND type = push
    before_script:
    - eval $(docker run --rm -i -e AWS_ACCESS_KEY_ID=$ECR_AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$ECR_AWS_SECRET_ACCESS_KEY quay.io/keboola/aws-cli ecr get-login --region us-east-1 --no-include-email)
    - docker pull "${ECR_REGISTRY}:${ECR_TAG}"
    script:
    - >-
      docker run --rm
      -e "AWS_ACCESS_KEY_ID=${PROD_DEPLOY_AWS_ACCESS_KEY_ID}"
      -e "AWS_SECRET_ACCESS_KEY=${PROD_DEPLOY_AWS_SECRET_ACCESS_KEY}"
      -e "CLOUDFORMATION_ROLE_ARN=${PROD_CLOUDFORMATION_ROLE_ARN}"
      -e "LAMBDA_EXECUTION_ROLE_ARN=${PROD_LAMBDA_EXECUTION_ROLE_ARN}"
      -e "KEBOOLA_STACK=aws-cloudtrail-slack-hook"
      -e "PAPERTRAIL_PORT=${PROD_PAPERTRAIL_PORT}"
      -e "REGION=${PROD_REGION}"
      -e "SERVICE_NAME=${PROD_SERVICE_NAME}"
      -e "SLACK_URL=${PROD_SLACK_URL}"
      -e "STAGE=prod"
      -e "TIME_ZONE=${PROD_TIME_ZONE}"
      -e "WATCHED_EVENTS=${PROD_WATCHED_EVENTS}"
      "${ECR_REGISTRY}:${ECR_TAG}" serverless deploy
