sudo: true
language: bash
services:
- docker

before_install:
- docker -v
- echo $TRAVIS_COMMIT
- export ECR_REPOSITORY=keboola/aws-cloudtrail-slack-hook
- export ECR_REGISTRY="061240556736.dkr.ecr.us-east-1.amazonaws.com/${ECR_REPOSITORY}"
- export ECR_TAG=stage-$TRAVIS_COMMIT

jobs:
      include:
      - stage: install
        before_script:
        - docker build -t $ECR_REPOSITORY .
        - docker tag $ECR_REPOSITORY:latest "${ECR_REGISTRY}:${ECR_TAG}"
        script: skip
      - stage: lint
        script:
        - docker run --rm "${ECR_REGISTRY}:${ECR_TAG}" yarn test:lint
      - stage: tests
        script:
        - docker run --rm
              -e SLACK_URL
              "${ECR_REGISTRY}:${ECR_TAG}" yarn test:unit
      - stage: deploy
        if: branch = master
        script:
        - >-
              docker run --rm
              - "AWS_ACCESS_KEY_ID=${PROD_DEPLOY_AWS_ACCESS_KEY_ID}"
              - "AWS_SECRET_ACCESS_KEY=${PROD_DEPLOY_AWS_SECRET_ACCESS_KEY}"
              - "KEBOOLA_STACK=aws-cloudtrail-slack-hook"
              - "PAPERTRAIL_PORT=${PROD_PAPERTRAIL_PORT}"
              - "REGION=${PROD_REGION}"
              - "SERVICE_NAME=${PROD_SERVICE_NAME}"
              - "SLACK_URL=${PROD_SLACK_URL}"
              - "STAGE=prod"
              - "TIME_ZONE=${PROD_TIME_ZONE}"
              - "WATCHED_EVENTS=${PROD_WATCHED_EVENTS}"
              "${ECR_REGISTRY}:${ECR_TAG}" serverless deploy
