version: "2"

services:

  deploy:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    working_dir: /code
    environment:
      - "AWS_ACCESS_KEY_ID=${DEV_DEPLOY_AWS_ACCESS_KEY_ID}"
      - "AWS_SECRET_ACCESS_KEY=${DEV_DEPLOY_AWS_SECRET_ACCESS_KEY}"
      - "CLOUDFORMATION_ROLE_ARN=${DEV_CLOUDFORMATION_ROLE_ARN}"
      - "LAMBDA_EXECUTION_ROLE_ARN=${DEV_LAMBDA_EXECUTION_ROLE_ARN}"
      - "KEBOOLA_STACK=aws-cloudtrail-slack-hook"
      - "PAPERTRAIL_PORT=${DEV_PAPERTRAIL_PORT}"
      - "REGION=${DEV_REGION}"
      - "SERVICE_NAME=${DEV_SERVICE_NAME}"
      - "SLACK_URL=${DEV_SLACK_URL}"
      - "STAGE=dev"
      - "TIME_ZONE=${DEV_TIME_ZONE}"
      - "WATCHED_EVENTS=${DEV_WATCHED_EVENTS}"
    command: >
             sh -c '
             serverless deploy
             '

  deploy-prod:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - .:/code
    working_dir: /code
    environment:
    - "AWS_ACCESS_KEY_ID=${PROD_DEPLOY_AWS_ACCESS_KEY_ID}"
    - "AWS_SECRET_ACCESS_KEY=${PROD_DEPLOY_AWS_SECRET_ACCESS_KEY}"
    - "CLOUDFORMATION_ROLE_ARN=${PROD_CLOUDFORMATION_ROLE_ARN}"
    - "LAMBDA_EXECUTION_ROLE_ARN=${PROD_LAMBDA_EXECUTION_ROLE_ARN}"
    - "KEBOOLA_STACK=aws-cloudtrail-slack-hook"
    - "PAPERTRAIL_PORT=${PROD_PAPERTRAIL_PORT}"
    - "REGION=${PROD_REGION}"
    - "SERVICE_NAME=${PROD_SERVICE_NAME}"
    - "SLACK_URL=${PROD_SLACK_URL}"
    - "STAGE=prod"
    - "TIME_ZONE=${PROD_TIME_ZONE}"
    - "WATCHED_EVENTS=${PROD_WATCHED_EVENTS}"
    command: >
      sh -c '
      serverless deploy
      '

  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    working_dir: /code
    environment:
      - "SLACK_URL=${DEV_SLACK_URL}"
    command: >
             sh -c '
             yarn test
             '
